import org.junit.jupiter.api.Test;
import java.math.BigDecimal;
import static org.junit.jupiter.api.Assertions.*;

class OrderTest {

    @Test
    void testOrderCreationWithAutoGeneratedIdAndTimestamp() {
        Order order = new Order("client1", Ticker.GOOG, Side.BUY, 100L, new BigDecimal("2500.00"));

        assertNotNull(order.getOrderId());
        assertEquals("client1", order.getClientId());
        assertEquals(Ticker.GOOG, order.getTicker());
        assertEquals(Side.BUY, order.getSide());
        assertEquals(100L, order.getQuantity());
        assertEquals(new BigDecimal("2500.00"), order.getPrice());
        assertNotNull(order.getTimestamp());
    }

    @Test
    void testSetQuantity() {
        Order order = new Order("client1", Ticker.GOOG, Side.BUY, 100L, new BigDecimal("2500.00"));
        order.setQuantity(50L);
        assertEquals(50L, order.getQuantity());
    }
}
